name: map
description: Lightweight Map widget for flutter supporting different projections including EPSG4326/Mercator/WGS1984.
version: 1.3.4
homepage: https://pwa.ir
repository: https://github.com/xclud/flutter_map

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  latlng: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
